from . import detail_tax
from . import employee_bonus
from . import hr_contract
from . import hr_employee
from . import hr_leave_type
from . import hr_payslip
from . import hr_payslip_input_type
from . import hr_payslip_line
from . import hr_payslip_recurring
from . import hr_salary_rule
from . import hr_work_entry
