from . import account_salary
from . import certification_record
from . import clearance_reject
from . import employee_cl
from . import employee_clearance
from . import employee_eobi
from . import employee_resignation
from . import family_record
from . import hr_contract
from . import hr_employee
from . import hr_payslip
from . import hr_payslip_run
from . import hr_resume_line
from . import hr_settlement
from . import institute_institute
from . import insurance_policy
from . import insurance_record
from . import letter_letter
from . import other_document
from . import res_partner_bank
