# -*- coding: utf-8 -*-

{
    "name": "IVIS Employee Loan Management",
    "author": "IVIS",
    "website": "https://www.intelliVersal.com",
    "support": "info@intelliVersal.com",
    'category': 'Human Resources',
    "summary": "This module allow HR department to manage loan of employees.",
    "description": """This module allow HR department to manage loan of employees.""",
    "version": "18.0",
    "depends": ['account', 'hr', 'hr_payroll'],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        # 'wizard/emp_loan_report_views.xml',
        'report/ir_actions_report.xml',
        'report/loan_report_analysis_qweb_template.xml',
        # 'report/loan_report_from_wiz_template.xml',
        'views/account_payment_views.xml',
        'views/employee_loan_details_views.xml',
        'views/hr_employee_category_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_salary_rule_views.xml',
        'views/ir_rule.xml',
        'views/loan_installment_details_views.xml',
        'views/loan_policy_views.xml',
        # 'views/loan_prepayment_writeoff_views.xml',
        'views/loan_proof_views.xml',
        'views/loan_type_views.xml',

    ],
    "icon": '/ivis_hr_employee_loan/static/description/icon.png',
    "images": [],
    "price": 4000000,
    "currency": "EUR",
    "license": "OPL-1",
    "application": False,
    "auto_install": False,
    "installable": True,
}
