# -*- coding: utf-8 -*-

{
    "name": "IVIS Payroll Functions",
    "author": "IVIS",
    "website": "https://www.intelliVersal.com",
    "support": "info@intelliVersal.com",
    "category": "Payroll",
    "summary": "",
    "description": """""",
    "version": "18.0",
    "depends": ['hr_holidays', 'hr_contract', 'hr_payroll', 'hr_work_entry_contract', 'account_accountant',
                'ivis_hr_employee_loan', 'report_xlsx'],
    "data": [
        'security/ir.model.access.csv',
        'data/ir_config_parameter.xml',
        'data/ir_sequence.xml',
        'data/report_paperformat.xml',
        'wizard/custom_tree_report_views.xml',
        'wizard/employee_salary_sheet_views.xml',
        'wizard/payroll_reports_views.xml',
        'wizard/payroll_wizard_views.xml',
        'report/certificate_deduction_tax.xml',
        'report/ir_actions_report.xml',
        'report/payroll_reconciliation_report.xml',
        'report/payslip_pdf.xml',
        'report/performance_appraisal_form.xml',
        'report/provident_fund_deduction_certificate.xml',
        'report/salary_cheque.xml',
        'report/salary_sheet_report.xml',
        'views/employee_bonus_views.xml',
        'views/hr_contract_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_leave_type_views.xml',
        'views/hr_payslip_line_views.xml',
        'views/hr_payslip_views.xml',
        'views/hr_salary_rule_views.xml',
        'views/payroll_reports_menu.xml',
    ],
    "images": [],
    "price": 4000000,
    "currency": "EUR",
    "license": "OPL-1",
    "application": False,
    "auto_install": False,
    "installable": True,
}
