# -*- coding: utf-8 -*-

{
    "name": "IVIS Employee Details",
    "author": "IVIS",
    "website": "https://www.intelliVersal.com",
    "support": "info@intelliVersal.com",
    "category": "Employee",
    "summary": "Manage Employee Data",
    "description": """Manage Employee Data""",
    "version": "18.0",
    "depends": ['base_address_extended', 'hr', 'hr_contract', 'hr_payroll', 'account_accountant',
                'hr_work_entry_contract', 'ivis_payroll_functions'],
    "data": [
        'security/ir.model.access.csv',
        'data/mail_template.xml',
        'data/report_paperformat.xml',
        'data/scheduled_actions.xml',
        'report/employee_final_settlement_report_template.xml',
        'report/employee_profile_report_template.xml',
        'report/ir_actions_report.xml',
        'views/clearance_reject_views.xml',
        'views/employee_clearance_views.xml',
        'views/employee_resignation_view.xml',
        'views/hr_contract_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_payslip_employees_views.xml',
        'views/hr_payslip_run_views.xml',
        'views/hr_resume_line_views.xml',
        'views/ir_actions.xml',
        'views/res_partner_bank_views.xml',
    ],
    "images": [],
    "price": 4000000,
    "currency": "EUR",
    "license": "OPL-1",
    "application": False,
    "auto_install": False,
    "installable": True,
}
