# -*- coding: utf-8 -*-

{
    "name": "IVIS User Portal",
    "author": "IVIS",
    "website": "https://www.intelliVersal.com",
    "support": "info@intelliVersal.com",
    "category": "User",
    "summary": "User Portal",
    "description": """User Portal""",
    "version": "18.0",
    "depends": ['portal', 'hr', 'hr_attendance', 'hr_holidays', 'hr_payroll', 'mail', 'calendar', 'hr_zk_attendance',
                'ivis_leaves_chart', 'ivis_hr_employee_loan', 'aesl_appraisal_system'],
    "data": [
        'security/ir.model.access.csv',
        # 'views/employee.xml',
        'views/portal_menu.xml',
        'views/profile_template.xml',
        'views/profile_edit.xml',
        'views/attendance_template.xml',
        'views/leave_template.xml',
        'views/payslip_template.xml',
        'views/loan_template.xml',
        'views/password_reset.xml',
        'views/index.xml',
        'views/pin_reset.xml',
        'views/res_config_settings_views.xml',
        'views/appraisal_template.xml',
    ],
    "assets": {
        "web.assets_frontend": [
            '/ivis_user_portal/static/src/css/style.css',
            '/ivis_user_portal/static/src/js/events.js',
            '/ivis_user_portal/static/src/js/attendance.js',
            '/ivis_user_portal/static/src/js/change_request.js',
            '/ivis_user_portal/static/src/js/leave.js',
            '/ivis_user_portal/static/src/js/loan.js',
            '/ivis_user_portal/static/src/js/payslip.js',
            '/ivis_user_portal/static/src/js/appraisal.js',
        ],
    },
    "images": [],
    "price": 4000000,
    "currency": "EUR",
    "license": "OPL-1",
    "application": False,
    "auto_install": False,
    "installable": True,
}
