{
    "name": "Import Async",
    "author": "IVIS",
    "website": "https://www.intelliVersal.com",
    "support": "info@intelliVersal.com",
    "category": "Generic Modules",
    "summary": 'Import Async',
    "description": 'Import Async',
    "version": "18.0",
    "application": True,
    "depends": ["mail", "base_import", "base_sparse_field", "web"],
    "external_dependencies": {"python": ["requests"]},
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/queue_job_views.xml",
        "views/queue_job_channel_views.xml",
        "views/queue_job_function_views.xml",
        "wizards/queue_jobs_to_cancelled_views.xml",
        "wizards/queue_requeue_job_views.xml",
        "views/queue_job_menus.xml",
        "views/ir_cron.xml",
        "data/ir_cron.xml",
        "data/queue_job_function_data.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "/ivis_import_async/static/src/js/import.js",
            "/ivis_import_async/static/src/xml/import.xml",
        ],
    },
    "images": ["static/description/icon.png"],
    "price": 4000000,
    "currency": "EUR",
    "license": "OPL-1",
    "auto_install":False,
    "installable" : True,
    "post_init_hook": "post_init_hook",
    "post_load": "post_load",
}
